name: 'egypt_weather'
version: '1.0.0'
config-version: 2

profile: 'egypt_weather'

model-paths: ["models"]
analysis-paths: ["analyses"]
test-paths: ["tests"]
seed-paths: ["seeds"]
macro-paths: ["macros"]
snapshot-paths: ["snapshots"]

target-path: "target"
clean-targets:
  - "target"
  - "dbt_packages"

models:
  egypt_weather:
    silver:
      +materialized: incremental
      +schema: silver
      +on_schema_change: append_new_columns
      +tags: ['silver', 'incremental']
    gold:
      dimensions:
        +materialized: table
        +schema: gold
        +tags: ['dimension', 'run_once']
      facts:
        +materialized: incremental
        +schema: gold
        +on_schema_change: append_new_columns
        +tags: ['fact', 'incremental']