{{
    config(
        materialized='incremental',
        unique_key=['GOVERNORATE', 'DATE'],
        on_schema_change='append_new_columns'
    )
}}

WITH source_data AS (
    SELECT
        -- Standardize city names
        CASE 
            WHEN UPPER(TRIM(CITY)) = 'SIWAH' THEN 'MATROUH'
            WHEN UPPER(TRIM(CITY)) = 'SHARM EL SHEIKH' THEN 'SOUTH SINAI'
            WHEN UPPER(TRIM(CITY)) = 'ELWADY_ELGADED' THEN 'NEW VALLEY'
            WHEN UPPER(TRIM(CITY)) = 'EL WADI EL GEDID' THEN 'NEW VALLEY'
            WHEN UPPER(TRIM(CITY)) = 'SHARM _AL-SHAYKH' THEN 'SOUTH SINAI'
            WHEN UPPER(TRIM(CITY)) = 'ALEX' THEN 'ALEXANDRIA'
            WHEN UPPER(TRIM(CITY)) = 'SHARKIA' THEN 'SHARQIA'
            WHEN UPPER(TRIM(CITY)) = 'CAIRO' THEN 'CAIRO'
            WHEN UPPER(TRIM(CITY)) = 'SOUTH SINAI' THEN 'SOUTH SINAI'
            WHEN UPPER(TRIM(CITY)) = 'NEW VALLEY' THEN 'NEW VALLEY'
            WHEN UPPER(TRIM(CITY)) = 'GULF OF SUEZ' THEN NULL
            ELSE UPPER(TRIM(CITY))
        END AS GOVERNORATE,
        
        DATE,
        T2M AS TEMPERATURE_2M_MEAN,
        T2MDEW AS TEMPERATURE_2M_DEW_POINT,
        T2MWET AS TEMPERATURE_2M_WET_BULB,
        TS AS EARTH_SKIN_TEMPERATURE,
        T2M_RANGE AS TEMPERATURE_2M_RANGE,
        T2M_MAX AS TEMPERATURE_2M_MAXIMUM,
        T2M_MIN AS TEMPERATURE_2M_MINIMUM,
        QV2M AS SPECIFIC_HUMIDITY_2M,
        RH2M AS RELATIVE_HUMIDITY_2M,
        PRECTOTCORR AS PRECIPITATION_CORRECTED,
        PS AS SURFACE_PRESSURE,
        WS10M AS WIND_SPEED_10M_MEAN,
        WS10M_MAX AS WIND_SPEED_10M_MAXIMUM,
        WS10M_MIN AS WIND_SPEED_10M_MINIMUM,
        LOAD_TIMESTAMP
    FROM {{ source('bronze', 'WEATHER') }}
    
    {% if is_incremental() %}
        WHERE LOAD_TIMESTAMP > (
            SELECT COALESCE(MAX(LOAD_TIMESTAMP), '1970-01-01'::TIMESTAMP_NTZ)
            FROM {{ this }}
        )
    {% endif %}
)

SELECT 
    GOVERNORATE,
    DATE,
    TEMPERATURE_2M_MEAN,
    TEMPERATURE_2M_DEW_POINT,
    TEMPERATURE_2M_WET_BULB,
    EARTH_SKIN_TEMPERATURE,
    TEMPERATURE_2M_RANGE,
    TEMPERATURE_2M_MAXIMUM,
    TEMPERATURE_2M_MINIMUM,
    SPECIFIC_HUMIDITY_2M,
    RELATIVE_HUMIDITY_2M,
    PRECIPITATION_CORRECTED,
    SURFACE_PRESSURE,
    WIND_SPEED_10M_MEAN,
    WIND_SPEED_10M_MAXIMUM,
    WIND_SPEED_10M_MINIMUM,
    LOAD_TIMESTAMP,
    CURRENT_TIMESTAMP() AS TRANSFORM_TIMESTAMP
FROM source_data
WHERE GOVERNORATE IS NOT NULL
    AND DATE IS NOT NULL